version: "1"
services:
  frontend:
    build:
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"

  backend:
    build:
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
