# Use the official Python image as a starting point
FROM python:3.8

# Set the working directory for the backend
WORKDIR /app/backend

# Clone the backend code from GitHub
RUN git clone https://github.com/sharmanvarun/construction-backend.git .

# Install backend dependencies
RUN pip install -r requirements.txt

# Expose the port the Django app runs on (adjust as needed)
EXPOSE 8000

# Start the Django app
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
