# Generated by Django 4.2.1 on 2023-09-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='material',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='material_images/'),
        ),
        migrations.AlterField(
            model_name='material',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
